### ISSUE TITLE
Question on Latest Display

### ISSUE THREAD

**Issue by teambound** [ventrian/Property-Agent#1]
This isn't so much of an issue but I need help with a display using the **latest** module.  I would like to use the free form custom display option using responsive html but I would like to display the properties in a horizontal list.  I have tried many things but can get the display horizontal.

Can anyone help with an example?

Thanks!

**Comment by sjmcculloch** [comment]
have you tried just some simple CSS floated left - you do have it on the layout mode that doesn't add html for tables too right?
