### ISSUE TITLE
Error Opening Solution for the First Time

### ISSUE THREAD

**Issue by WillStrohl** [ventrian/Property-Agent#10]
Steps to Reproduce:

1. Fork the repo into another account.
2. Clone the repo to the local development computer in a new and empty folder.
3. Open the project in Visual Studio (I used 2017).

Expected Behavior:
The project opens without error.

Actual Behavior:
The error below occurs, and the website project doesn't load.  

http://www.ventrian.it : error  : Error opening web http://www.ventrian.it. Unable to open the Web site 'http://www.ventrian.it'.  The Web server 'http://www.ventrian.it' could not be found.

**Comment by Scippy** [comment]
To make working www.ventrian.it you must address it on your local dnn PA development enviroment adding binding on IIS and this line on your host file:
127.0.0.1 www.ventrian.it
