### ISSUE TITLE
Property Type Listing not working when SSL (HTTPS)

### ISSUE THREAD

**Issue by djamell** [ventrian/Property-Agent#15]
I'm using the Scippy Version 01.09.00 on DNN 8.0.4 and when SSL is enabled (https://) the page will not load and displays a "The page isn’t redirecting properly" or "ERR_TOO_MANY_REDIRECTS" error.

The URL that fails looks like this:
https://nunneleewright.com/Properties/agentType/ViewType/PropertyTypeID/20

Accessing the URL without SSL (http://) works fine.

Please advise!

**Comment by djamell** [comment]
Update:  I found that if I uncheck the "Do Redirect?" option under SEO Settings the error does not occur.

**Comment by Scippy** [comment]
Hi djamell, for optimal usage of PA URLs I suggest you to use sachatrauwaen [OpenUrlRewriter](https://github.com/sachatrauwaen/OpenUrlRewriter) with [PropertyAgent Provider](https://github.com/sachatrauwaen/PropertyAgent_OpenUrlRewriter/releases).
