### ISSUE TITLE
Adobe Flash is going away!  Need New Solution for Uploading Photos!

### ISSUE THREAD

**Issue by djamell** [ventrian/Property-Agent#17]
I'm using the Scippy Version 01.09.00 on DNN 8.0.4.

Adobe Flash will stop working in all browsers soon.  Is there a plan to replace the Photo Upload?

Please say yes.

**Comment by Scippy** [comment]
Hi djamell,
The feature is already present!
Go in Layout Settings, Form Settings, Upload Mode

**Comment by mortezakermani** [comment]
They at benvis.com replaced flash upload with javascript upload:

https://store.dnnsoftware.com/home/product-details/ventrian-property-agent-patch
