### ISSUE TITLE
Project maintainer(s)

### ISSUE THREAD

**Issue by bdukes** [ventrian/Property-Agent#19]
@sjmcculloch what do you think about adding @Scippy as a maintainer on this project (as you have with @skamphuis on the News Articles repo)?  It'd be nice to be able to move forward with some of the improvements from #18 (recognizing that there's also a track record with #4).

Thanks for any thoughts!

**Comment by sjmcculloch** [comment]
@bdukes - I've added @Scippy as a maintainer.

**Comment by bdukes** [comment]
Thanks!

**Comment by Scippy** [comment]
Thanks @bdukes for your input and thanks @sjmcculloch for my new role as maintainer.
I want to clarify that I am a webmaster and not a developer moreover with little knowledge of Github. Despite this, I managed to carry this project forward and make it usable even in the latest versions of DNN with many improvements. I hope I will be able to do a good job here without causing trouble.
What I would like to tell @sjmcculloch is that his project has allowed me to create my own small company and to do business by creating sites based on this module, in other words his work has changed my life. I have been a Ventrian Gold Member for many years, and the day Scott inexplicably abandoned Ventrian projects has been a sad day for me. However, I am also infinitely grateful to him for making the project free on GitHub, avoiding his certain death.
What I would like to ask Scott is if he had a backup of his old web site ventrian.com and if he wanted to contact me privately at scippy@gmx.com and pass me that backup I would like put it back online (and there I would be able to do a good job), in this way I would like to restore a reference point for documentation and above all for the countless posts in the two forums that have been enriched with useful posts for years. Of course it would be my free contribution to keep this magnificent work @sjmcculloch has done alive.
