### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TheCakeGit** [ventrian/Property-Agent#2]
Hi

I'm trying to find documentation such as the template guide for Property Agent. Same applies for the other modules such as news articles, galleries. Does anybody have a URL?

Can we also have a readme like newsarticles showing tokens?
https://github.com/ventrian/News-Articles/blob/master/README.md

Thanks.

**Comment by Scippy** [comment]
[PropertyAgentTemplateGuide.pdf](https://github.com/ventrian/Property-Agent/files/1471020/PropertyAgentTemplateGuide.pdf)
[PropertyAgentAdminGuide.01.00.00.pdf](https://github.com/ventrian/Property-Agent/files/1471024/PropertyAgentAdminGuide.01.00.00.pdf)

**Comment by TheCakeGit** [comment]
Thanks very much :)

**Comment by Scippy** [comment]
Added Wiki page
