### ISSUE TITLE
SWF file upload not working

### ISSUE THREAD

**Issue by malanisourabh** [ventrian/Property-Agent#28]
Hello Support,

We have website in DNN version 7.4.2. We are using Ventrian Property-Agent module version 1.8.12. 

We are facing issue in  Upload Photo(s) section. Right now it is showing SWF file upload control for upload photo. As you know that Adobe reader remove support from flash player since 31st December 2020 so it stops and nothing happen when click on it.

We have checked the folder "PropertyAgent/Controls" and found there are two controls for upload photo i.e "UploadPhotoSWF.ascx" and "UploadPhotoStandard.ascx". How we can change the file upload control in place of SWF so it open Photo Standard layout so that we can upload images.

I attached screenshots for more information. Please find this.

Please suggest and help regarding this issue. Any advice would be greatly appreciated!

Thank you in advance

Best Regards,
Sourabh Malani

![Screenshot_1](https://user-images.githubusercontent.com/42605175/105594098-13f3a680-5db9-11eb-81f6-6bf32f84664f.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/42605175/105594124-15bd6a00-5db9-11eb-8706-57c8b913c153.jpg)

**Comment by Scippy** [comment]
PA 1.10.13 is released with HTML5 photo upload option
In 1.8.12 version you can ony change photo upload to standard by layout settings photo options

**Comment by malanisourabh** [comment]
Hello Support,

Thank you for your quick response.

As per mentioned we have found settings under layout settings, now file uploading is working but it is allowing upload single image at a time.

Our website is in DNN 7.4.2 version and the latest released version of Property Agent is 1.10.13, so can we install this upgrade module on our website (DNN 7.4.2) so that we can use HTML5 photo upload option. Please confirm about this. 

Thank you in advance

Best Regards,
Sourabh Malani

**Comment by Scippy** [comment]
Yes you can, but make before a backup for any possible issue or try before in a test enviroments.
Latest PA version is compatible with DNN 7.4.2, I'm actually work in some my old installation with it

**Comment by djamell** [comment]
Hi Scippy - Off topic (sorry) but is there any way you could make the same change to Ventrian File Links?

**Comment by Scippy** [comment]
File link is already with standard no flash upload

**Comment by Scippy** [comment]
Sorry I missed that you mean file links module and not file link custom field
About file link module I've no plan to update

**Comment by malanisourabh** [comment]
Hello Support,

Thank you for confirmation.

We have installed the latest release verison of module. Everthing is working well.

Thank you.

Best Regards,
Sourabh Malani
