### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by TheCakeGit** [ventrian/Property-Agent#3]
Hello

I'm just wondering if we will see at least just one release of all the Ventrian modules.
PA is basically my fav module, it would be very nice to be able to upgrade them.

I think if everybody could get up to a base level, then contributions are far more likely to happen here. I appreciate all of this takes time and there are no longer subscriptions available, so please only view this as encouragement, regardless I'd love to see one release of the main modules here, at the very least otherwise I fear the death of it :)

For instance I'm currently running:
PA 1.8.12.
News Articles: 0.9.11
Gallery: 2.4.39

I'd just like to say these modules have done me extremely well throughout the years I do appreciate it.
Sites like this one, which runs PA on over half of it's pages would be a lot harder and would not be as good.
http://www.ajantamusic.com/

Thanks

Alex

**Comment by TheCakeGit** [comment]
So I got this notified totoday:
https://github.com/ventrian/Property-Agent/pull/4
**"PA Release 01.09.00 now compatible with DNN8"**

I wonder if it's still compatible with 7.4.2 ?

Was there supposed to be a release here?
https://github.com/ventrian/Property-Agent/releases

I am assuming something needs to happen first.

Thanks :)

**Comment by Scippy** [comment]
Hi, you can find my new release here: https://github.com/Scippy/Property-Agent/releases
I've pulled my modified code on ventrian:master, waiting for Scott approve
The new release is now compatible with DNN7/8.

**Comment by TheCakeGit** [comment]
Awesome!!!

**Comment by TheCakeGit** [comment]
Should this update OK from PA 1.8.12 ?
Thx :)

**Comment by Scippy** [comment]
Yes, sure. But it is always good practice to make a backup first or make a local test.

**Comment by sjmcculloch** [comment]
I've just merged the latest in from Scippy (thank you!)

**Comment by sjmcculloch** [comment]
I'll fix the releases up shortly.

**Comment by davegambino** [comment]
Does this new release have an import / export option?

I am using this module as a Project Gallery for a construction company.  The customer has about 100 Projects in the module on Portal#1.  I am redesigning the site for them with an updated theme and exported a site template of Portal#1 and Published a new Portal#2 on the same host.

However, PA setup and content did not move over to the new portal.

Does anyone know how i can export content and template from the module on Portal #1 and Import it to Portal#2?

Thanks for any help.

**Comment by david-poindexter** [comment]
@davegambino I do not see anywhere in the code where PA implements IPortable (which allows for the core DNN module import/export capability).  That would be a GREAT enhancement for someone to contribute though!

**Comment by davegambino** [comment]
@nvisionative Do you believe this can be accomplished by running SQL scripts?

**Comment by david-poindexter** [comment]
@davegambino the short answer is "yes".  The long answer is that you would have to clearly understand where all your data resides within the PA tables and you'll have to do some work to map IDs between your two DNN instances.  Then it should be a matter of scripting it all out and testing in a DEV environment to ensure it is working as expected.  @sjmcculloch do you see any issues with this approach?  Or do you have another recommendation?

**Comment by Scippy** [comment]
Yes, it is possible, but you’ve also to manual copy all properties photos files in the new right portals2 folder. Also remember that ID is not the only field to change in the SQL script, but you must update also user ID properties owner

**Comment by teambound** [comment]
Never mind I just found the show all users checkbox. 

I just upgraded my site to dnn 8.0.4 and updated to the latest release of PA by Scippy.  When I am logged in everything is ok but when I log out no properties show up.

**Comment by Scippy** [comment]
to show properties to unauthenticated users you need to set the new colum name 'OnlyForAuthenticated' on Property table to 'True' otherways all properties will be visible only to authenticated users.
You can use this script to update in one shot:
UPDATE Ventrian_PropertyAgent_Property
SET OnlyForAuthenticated = 'True'
You can set this value for each property with edit properties feature, you can find the new option at the end of edit near feature checkbox

**Comment by toshno** [comment]
> Hi, you can find my new release here: https://github.com/Scippy/Property-Agent/releases
> I've pulled my modified code on ventrian:master, waiting for Scott approve
> The new release is now compatible with DNN7/8.

Any plan to get it to work with DNN 9.2?

**Comment by JoeAucoin** [comment]
I also have a need for an update to support DNN 9.2!
