### ISSUE TITLE
properties are not being listed for public users

### ISSUE THREAD

**Issue by ufoloko** [ventrian/Property-Agent#30]
I updated module to the last version and i can see properties just if im logged in, but if i logout i cant list properties

Please help

**Comment by Scippy** [comment]
Refer to issue#9
https://github.com/ventrian/Property-Agent/issues/9
if you don't have many properties you can also edit each manually and check only for authenticated user checkbox

**Comment by ufoloko** [comment]
Thanks, i already noticed that
