### ISSUE TITLE
File Upload Not Working

### ISSUE THREAD

**Issue by JoeAucoin** [ventrian/Property-Agent#32]
I've tested in Edge, Edge in Internet Explorer mode, and Chrome and nothing works for "File Upload". I am trying to upload PDF files. Image upload is working fine.

**Comment by Scippy** [comment]
Hi Joe, depending on PA release, you've to check in Layout Setting the max upload size

**Comment by JoeAucoin** [comment]
you're the best . . . that was exactly the issue. I did not have a value in max upload size. It works now. Thanks (grazie)
