### ISSUE TITLE
Keeping querystring items

### ISSUE THREAD

**Issue by fprati** [ventrian/Property-Agent#5]
Hello,
the suggested method to keep querystring out of the URL path does not seem to work with P.A. on DNN 9.1.1: the appended ?gclid= parameter gets rewritten on pages containing properties whilst they are kept unchanged.
I followed these recommendations: http://www.dnnsoftware.com/wiki/keeping-querystring-items-out-of-the-url-path-in-dnn

Can others corfirm and what can a possible fix or workaround be, please?

Regards
Franco

**Comment by Scippy** [comment]
Try with Open Url Rewriter, I've posted on releases also thr provider for PA
