### ISSUE TITLE
Templates Not Selected After Upgrade

### ISSUE THREAD

**Issue by WillStrohl** [ventrian/Property-Agent#6]
Is anyone else experiencing this?  How are you resolving it right now?

DNN: 07.04.02
PA Verion:  01.08.12
Upgrading to:  01.09.00

Steps to Reproduce:

1. Clean installation of DNN.
2. Install & configure an older version of PA.
3. Upgrade to PA 01.09.00.
4. View a page with PA on it.

Expected Behavior:
Existing content appears as it did prior to the upgrade on all instances of the module.

Actual Behavior:
Almost randomly, some existing content is no longer shown, and the "Select Template" is shown instead.  It doesn't happen to all instances though.

**Comment by Scippy** [comment]
Hi Will, I've tried step by step but I'm no able to replicate this issue.
Do you have the .zip with full DNN installation before upgrading to PA 01.09.00?...so I can have a try for you.
However I notice to you that if you install PA 01.09.00 on existing installation with old PA version, to show all properties to all users you need to set the new colum name 'OnlyForAuthenticated' on Property table to 'True' otherways all properties will be visible only to authenticated users.
You can use this script to update in one shot:
UPDATE       Ventrian_PropertyAgent_Property
SET                OnlyForAuthenticated = 'True'

**Comment by WillStrohl** [comment]
I'm not going to be able to provide the website to you, but one of the clients that is experiencing this seems to see occur repeatedly since the upgrade.  I'm not sure why.  It's very odd.  They have to occasionally go back to the website and re-associate the template to specific instances of the module.

**Comment by Scippy** [comment]
Open under PA menu Edit Layout Files, what you can see here about Current Template?
It is difficoultus to debug without having the issue.

**Comment by WillStrohl** [comment]
It apparently has stopped duplicating itself, but the template was definitely no longer selected after upgrade.
