### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by teambound** [ventrian/Property-Agent#8]
Glad to see work being done to PA.  I use it extensively on my site. There were a couple of enhancements that I have been asking for years but they never made the list. Here they are in hopes that others find them useful enough to add to the roadmap

1. In settings under form settings the Bind Expiry to a date field expires the property at 12:01am so you won't see the property for the  whole day. It would be helpful to add an expiry time.

2. The admin has the ability to clone a property. It would be great to add that option to permissions so potentially other users can clone.

3. It would be great to be able to print the shortlist or be able to email it to the user. 

Thanks!

**Comment by Scippy** [comment]
1. Can you give more detail?
2. All roles with the ability to edit property it is right that they have also clone ability
3. You are able to do with [CONTACTFORM] token in view property layout file
