### ISSUE TITLE
After Upgrade, Template Content not Rendered to Unauthenticated Visitors

### ISSUE THREAD

**Issue by WillStrohl** [ventrian/Property-Agent#9]
Upgraded from PA 01.08.12 to 01.09.00 and DNN from 07.04.02 to 09.01.01.

When I did, several template settings were missing (like in issue #6), but we updated the setting to show the content.   However, a very odd thing that's occurring is that the content in the template is only showing to authenticated visitors.  When viewing the page as an unauthenticated visitor, the content isn't even in the HTML, so there's nothing to render to the page.

I've tried adding Unauthenticated and Unverified roles to the module and override the permissions to show the content, but this didn't work.  

Any ideas why this would be happening?

**Comment by Scippy** [comment]
to show properties to unauthenticated users you need to set the new colum name 'OnlyForAuthenticated' on Property table to 'True' for each property that must be visible to anonymous user, all properties setted to false will be visible only to authenticated users in any role.
You can use this script to update in one shot:
UPDATE Ventrian_PropertyAgent_Property
SET OnlyForAuthenticated = 'True'

You can also set this value for each property on PA edit properties feature, you can find the new option at the end of edit form near feature checkbox.

Any property added after the PA update is on default visible to all users.

**Comment by WillStrohl** [comment]
Interesting... Was this something that should have been done in the past, or is this a new feature?

**Comment by WillStrohl** [comment]
Never mind... I just noticed "new column name"  :D 

Why did this default to not showing to authenticated users, when that was already the default before upgrade?

**Comment by WillStrohl** [comment]
This worked beautifully, by the way.  For anyone running into this in the future, here are the queries to run to resolve this:

In SSMS:  
`UPDATE [Ventrian_PropertyAgent_Property] SET [OnlyForAuthenticated] = 1;`

In the DNN SQL Console:
`UPDATE {databaseOwner}[{objectQualifier}Ventrian_PropertyAgent_Property] SET [OnlyForAuthenticated] = 1;`

**Comment by Scippy** [comment]
Because it is a little mistake on the update but only for properties already added before the update.
It is a new feature I’ve added, it is very useful to add hidden property for anonymous users that must be visible only to registered users in any roles.

**Comment by WillStrohl** [comment]
Sounds good.  Thanks, @Scippy!  :)

**Comment by JoeAucoin** [comment]
Hey Scrippy . . . . Any chance you could make this compatible for latest version of DNN?

**Comment by Scippy** [comment]
Hi Joe, my business is still around DNN 8.0.4 but in the next future I think to update anyway PA to DNN 9+
Ventrian PA is the best DNN module that make me able to solve any problem and it is my interest to make it compatible with latest DNN release.
If you need in short time of the update version you can find a patch [here](https://store.dnnsoftware.com/home/product-details/ventrian-property-agent-patch)

**Comment by JoeAucoin** [comment]
Hi Skippy,

 

Thanks for your reply. I also agree that PA is one of the most versatile/best modules available!

 

I recently purchased your suggested patch, but I was running into errors with it. Just today, I have been working with developer to resolve issues and we are getting close to success for up to DNN 9.4.1 compatibility. Only issue remaining is getting maps to work.

 

I appreciate your support to this Ventrian module and I hope to see 9.4 compatibility available at GitHub.

 

Thank you,

 

Joe

 

 

******************************************
Joseph M. Aucoin, Owner
Global Internet Business Solutions, LLC
P.O. Box 2342
Brewster, MA 02631
http://www.gibs.com <http://www.gibs.com/> 
Business (774) 323-3176
Fax: (508) 714-0678
Cell: (508) 237-2745
******************************************
